TARGETS := khetplayer

LOCKER=/afs/csail/proj/courses/6.172
CC := icpc
CXX := icpc 
# You can add -Werr to GCC to force all warnings to turn into errors
CXXFLAGS := -g -Wall -std=c++0x 
LDFLAGS = -ltbb

HEADERS := \
	khet.h \
	KhetState.h \
	eval.h \
	ABSearch.h \
	Abort.h \
	globals.h\

# Blank line ends list.

# If you add a new file called "filename.c", you should
# add "filename.o \" to this list.
OBJS := \
	eval.o \
	KhetState.o \
	khet.o

# Blank line ends list.

OLDMODE := $(shell cat .buildmode 2> /dev/null)
ifeq ($(DEBUG),1)
CFLAGS := -DDEBUG -O0 $(CFLAGS)
CXXFLAGS := -DDEBUG -O0 $(CXXFLAGS)
ifneq ($(OLDMODE),debug)
$(shell echo debug > .buildmode)
endif
else
CFLAGS := -DNDEBUG -O3 $(CFLAGS)
CXXFLAGS := -DNDEBUG -O3 $(CXXFLAGS)
ifneq ($(OLDMODE),nodebug)
$(shell echo nodebug > .buildmode)
endif
endif

# make all targets specified
all: $(TARGETS)
khetplayer: $(OBJS) $(HEADERS) 
	$(CXX) $(LDFLAGS) $(OBJS) -o $@

# compile objects

# pattern rule for building objects
%.o: %.cxx %.h $(HEADERS) .buildmode Makefile ABSearch.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

# remove targets and .o files as well as output generated by CQ
clean:
	$(RM) $(TARGETS) $(OBJS) *.std* .buildmode
	
